void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
void _putchar();
int _solve(int guess, int n);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
int check_for_pali(char *s, int n, int l);
int length(char *s);
